package:
  name: nexusformat
  version: "0.7.4"

source:
  git_url: https://github.com/nexpy/nexusformat.git
  git_tag: v0.7.4

build:
  entry_points:
    - nxstack = nexusformat.scripts.nxstack:main
    - nxduplicate = nexusformat.scripts.nxduplicate:main
    - nexusformat = nexusformat.scripts.nexusformat:main
  number: 0

requirements:
  build:
    - python >=3.6
    - setuptools
    - setuptools_scm

  run:
    - python >=3.6
    - numpy
    - scipy
    - h5py

test:
  commands:
    - nexusformat --version
    - pytest

about:
  home: http://nexpy.github.io/nexusformat/
  license: BSD License
  summary: 'nexusformat: Python API to access NeXus data'
